version: "3.7"
services:
  nginxserv:
#    user: "1000:1001"
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    tty: true
    links:
      - php-fpm

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
        - "33061:3306"
    volumes:
      - ./storage/mysqldata:/var/lib/mysql

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/app
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"

  php-cli:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/app
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"

  redis:
    image: redis:3.0
    ports:
      - "63791:6379"

  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/app
    tty: true
